name: Deploy to Production

on:
  push:
    branches: [ main, master ]  # Ejecutar en push a main o master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      # Build step omitido porque la aplicaci贸n no necesita compilaci贸n
      # - name: Build
      #   run: npm run build

      # Tests omitidos porque no hay pruebas configuradas
      # - name: Run tests
      #   run: npm test

      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            # Primero, actualiza los archivos de configuraci贸n con secrets
            cd /home/proyectos/api_project/mongo_clients
            
            # Actualiza los archivos de configuraci贸n
            echo "MONGO_URI=${{ secrets.MONGO_URI }}" > .env
            echo "PORT=${{ secrets.PORT }}" >> .env
            
            # Actualiza ecosystem.config.js con los valores de secrets
            cat > ecosystem.config.js << 'EOL'
            module.exports = {
              apps: [{
                name: "mongo_users",
                script: "./dist/app.js",
                interpreter: "ts-node",
                env: {
                  NODE_ENV: "production",
                  PORT: ${{ secrets.PORT }},
                  MONGO_URI: "${{ secrets.MONGO_URI }}"
                }
              }]
            };
            EOL
            
            # Ejecuta el script de despliegue
            bash ./deploy.sh