name: Deploy to Production

on:
  push:
    branches: [ main, master ]  # Ejecutar en push a main o master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      # Tests omitidos porque no hay pruebas configuradas
      # - name: Run tests
      #   run: npm test

      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            # Asegurarse de que las herramientas necesarias están disponibles
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # Cargar NVM si está instalado
            
            # Navegar al directorio de la aplicación
            cd /home/${{ secrets.SSH_USERNAME }}/api_project/mongo_clients
            
            # Actualiza los archivos de configuración
            echo "MONGO_URI=${{ secrets.MONGO_URI }}" > .env
            echo "PORT=${{ secrets.PORT }}" >> .env
            
            # Actualiza ecosystem.config.js con los valores de secrets
            cat > ecosystem.config.js << 'EOL'
            module.exports = {
              apps: [{
                name: "mongo_users",
                script: "./dist/app.js",
                interpreter: "ts-node",
                env: {
                  NODE_ENV: "production",
                  PORT: ${{ secrets.PORT }},
                  MONGO_URI: "${{ secrets.MONGO_URI }}"
                }
              }]
            };
            EOL
            
            # Obtén los últimos cambios
            git fetch origin main
            git reset --hard origin/main
            
            # Instala dependencias y construye
            npm ci
            npm run build
            
            # Reinicia la aplicación con PM2
            if command -v pm2 &> /dev/null; then
              pm2 reload ecosystem.config.js || pm2 start ecosystem.config.js
            else
              echo "PM2 no está instalado, instalándolo..."
              npm install -g pm2
              pm2 start ecosystem.config.js
            fi
            
            # Muestra estado de la aplicación
            pm2 status